### ISSUE TITLE
Logon schedule not working after restart

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/TaskbarX#140]
I disabled run at startup and used new task schedule option instead.

- FalconX was running
- Restarted my PC
- Falcon did not do anything to the taskbar, but its process was shown as running in the task manager
- When I logged off and then back in (no restart), it started normally and worked as expected

**Comment by Neobond** [comment]
Same here, I only enabled it (and changed it to "On startup" rather than login, because FalconX appears to be the last app that starts when Windows has booted, it tales minutes for the taskbar to center and I really only came here to find out if others experience the same slowness.

**Comment by robindrost** [comment]
Same issue here. After a reboot I have to start it manually.

**Comment by Cabola** [comment]
I've noticed it can hang in centring unless you have an application running on other monitors than the primary. Ex. in my case I have 3 monitors (2x24" and 1x49"); 2 above my primary, like so:
|2||3|
|-1-|

if I launch a txt file (which opens on monitor 2) and a file explore (which opens on monitor 3), then all 3 taskbars gets centred. But not till I open an application on both secondary monitors. If it's just 1 of them that has an application running then only that monitors taskbar is centred and the 2 others remain untouched..

**Comment by Neobond** [comment]
I hate this new version that stops randomly by itself and the "stop" "restart" options never work (they just shut off and restart windows explorer) and there is no tray icon anymore. I am downgrading.

**Comment by ChrisAnd1998** [comment]
@Neobond  Should be fixed now ;)

**Comment by Neobond** [comment]
I installed 1.3.9.0 still getting a smartscreen warning when running falconx and falconxsettings. I hope the next version places settings back in the systray.

![SNAG-0011](https://user-images.githubusercontent.com/42996358/72680238-da0e0700-3ab7-11ea-9d04-7bc2dbe15729.png)

**Comment by ChrisAnd1998** [comment]
How about 1.4.1.0?

**Comment by LastReaction** [comment]
I'm also having an issue with FalconX not starting at log on via the task scheduler. The last run result error message in the task scheduler application is this: 0xE0434352. I've also tried putting a FalconX shortcut in the Startup folder and that also did not work.

**Comment by LastReaction** [comment]
@ChrisAnd1998 I have figured out the issue. It turns that that you need to add a delay to the task so that it does not interfere with other startup processes. I added a delay of 30 seconds to the task and that seems to have fixed the problem. It doesn't start up instantly on login as intended, but it does actually load automatically now after 30 secs instead of me having to do it manually.

**Comment by ChrisAnd1998** [comment]
what if you type the seconds in? So replace "30 seconds" with "3 seconds" does that also work?

**Comment by LastReaction** [comment]
I'll give that a try shortly.

**Comment by ChrisAnd1998** [comment]
Great! Then i will implement it into the next update.
