### ISSUE TITLE
Secondary taskbars completely disappear on TBX startup

### ISSUE THREAD

**Issue by oOII-J4HN-IIOo** [ChrisAnd1998/TaskbarX#543]
**Describe the bug**
Upon startup of TBX (i.e. when logging on to my PC), the primary taskbar changes are made. Any additional taskbars I have on other virtual desktops completely disappear. The only way I can fix it is to stop TBX and restart Win Explorer.
**To Reproduce**
1. Stop TaskbarX (if it's not already running)
2. Start TaskbarX and apply any preferences 
3. Create/switch to another virtual desktop
4. See error (hopefully!)

**Expected behavior**
The taskbar is completely gone, not even hidden.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19042.746

**Additional context**
I use the acrylic taskbar option. While it does flicker from time to time, I have only now started seeing my secondary taskbar completely disappear.
I also noticed that when you press Win Key (or Alt) + Tab, there's a window created by TBX of the taskbar itself and I'm not sure why that is, but I know that's already a bug report here!

**Comment by guilhermesimoncello** [comment]
Running with the same issue, started today and everything that you described is happening.

Desktop (please complete the following information):
- Windows 10
- Version 20H2
- Build 19042.746

**Comment by lindhartsen** [comment]
Seeing the same issue here

**Desktop:**

- Windows 10
- Version 20H2
- Build 19042.746
- TaskbarX 1.6.5 (Windows Store install)

**Comment by ChrisAnd1998** [comment]
The ALT-TAB thingy is fixed in 1.6.6.0 pre-release ;)
Sadly i'am unable to reproduce the issue yet... in 1.6.5.0 i added a feature "total taskbar opacity" you sure both are 100% in the taskbar styling tab?

**Comment by oOII-J4HN-IIOo** [comment]
> @oOII-J4HN-IIOo @guilhermesimoncello @lindhartsen The ALT-TAB thingy is fixed in 1.6.6.0 pre-release ;)
> Sadly i'am unable to reproduce the issue yet... in 1.6.5.0 i added a feature "total taskbar opacity" you sure both are 100% in the taskbar styling tab?
> 
> Edit: Nevermind... i couldn't reproduce because the ALT-TAB fix also fixes this issue :).

Yep. both sliders to 100%. I don’t think I changed those sliders at all actually. But the problem wasn’t opacity, the taskbar had completely vanished (until I solved it in the way I mentioned in my post)...

Also, I don’t suppose pre-release versions are available via the Windows store (where I downloaded TBX originally)?

**Comment by guilhermesimoncello** [comment]
@ChrisAnd1998 thank you very much for the reply.
I'm running the version 1.6.5.0 from the MS Store, but I'm still have the issue happening as @oOII-J4HN-IIOo described.

**Comment by ChrisAnd1998** [comment]
@guilhermesimoncello You need to wait for update 1.6.6.0 to arrive to the store this can take some time. Mostly within a day max 3 days.

**Comment by guilhermesimoncello** [comment]
@ChrisAnd1998 thank you for clarifying that, I'll give a feedback as soon as I get the update. 
Cheers!

**Comment by guilhermesimoncello** [comment]
@ChrisAnd1998 latest update from MS fixed for me, thanks once again!
