### ISSUE TITLE
A thin line of desktop at bottom and left of taskbar

### ISSUE THREAD

**Issue by Russell-Ali** [ChrisAnd1998/TaskbarX#706]
<img width="960" alt="Screenshot 2021-06-30 185054" src="https://user-images.githubusercontent.com/82474455/123982530-28754400-d9d4-11eb-8f06-ec67382308bb.png">

**Comment by Russell-Ali** [comment]
I downgrade version to 1.6.9.0 and now it doesn't have that issue.

**Comment by DutchEclipse** [comment]
Same thing here.  shows a little bit of the wallpaper behind on the bottom.
![image](https://user-images.githubusercontent.com/83969413/124010029-96266d80-d9de-11eb-89b3-0d42bb5c036b.png)

**Comment by KotTenRat** [comment]
SAME but bottom and right

**Comment by Skulcrusherr** [comment]
yeah, I've noticed that too and would like a permanent fix, also when I center the icons the windows way, the icons on taskbar x go to the right instead of the left... would like that to be fixed as well!

**Comment by PZeide** [comment]
This is fixed in the [pre-release 1.7.10](https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0).

**Comment by GexerGex** [comment]
it's fix , but i have one on the right of the screen...

**Comment by T3kla** [comment]
It is not fixed. The gap on the bottom and right did disappear visually, but when the mouse all the way to the bottom right of the screen, the "show desktop" button will not be lit and can not be pressed. There is still a gap there.

**Comment by KotTenRat** [comment]
for now just downgrade to 1.6.9.0

**Comment by T3kla** [comment]
Downgrading to 1.6.9.0 did not solve the problem I just mentioned

**Comment by ChrisAnd1998** [comment]
To be able to focus on major/current bugs I had to close all issues. The issues section has gotten very messy to a point that I couldn't follow it anymore. Most issues are duplicates, very old or are already fixed/solved. Feel free to reopen this issue if you still have this issue on the latest version of TaskbarX to get my attention. All feature requests have been put in a list here: 💡| Feature requests #870 

I hope you understand ❤️
